// CLASSROOM TYPES
export const CLASS_LOADING = "CLASS_LOADING"
export const CLASS_LOADED = "CLASS_LOADED"
export const CLASS_LOAD_FAIL = "CLASS_LOAD_FAIL"

// BOOKS TYPES
export const BOOKS_LOADING = "BOOKS_LOADING"
export const BOOKS_LOADED = "BOOKS_LOADED"
export const BOOKS_LOAD_FAIL = "BOOKS_LOAD_FAIL"