// AUTHENTICATION TYPES
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCES = "LOGIN_SUCCES"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const REGISTER_SUCCES = "REGISTER_SUCCES"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

// ERROR TYPES
export const GET_ERROR = "GET_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"

// CLASSROOM TYPES
export const CLASS_LOADING = "CLASS_LOADING"
export const CLASS_LOADED = "CLASS_LOADED"
export const CLASS_LOAD_FAIL = "CLASS_LOAD_FAIL"
export const CLASS_ADDED = "CLASS_ADDED"

// BOOKS TYPES
export const BOOKS_LOADING = "BOOKS_LOADING"
export const BOOKS_LOADED = "BOOKS_LOADED"
export const BOOKS_LOAD_FAIL = "BOOKS_LOAD_FAIL"

// REQUEST TYPES
export const RESPONSE_LOADING = "RESPONSE_LOADING"
export const RESPONSE_LOADED = "RESPONSE_LOADED"
export const RESPONSE_ERROR = "RESPONSE_ERROR"